import logging
import os
import pwd
import subprocess

logger = logging.getLogger(__name__)

WG_DIR        = "/opt/hostpanel/plugins/wireguard"
WG_BIN        = f"{WG_DIR}/wg"
WG_QUICK      = f"{WG_DIR}/wg-quick"
WG_CONF       = f"{WG_DIR}/wg0.conf"
PEERS_DIR     = f"{WG_DIR}/peers"
SERVICE_NAME  = "hostpanel-wireguard"
SERVICE_DST   = f"/etc/systemd/system/{SERVICE_NAME}.service"
SUDOERS_DST   = f"/etc/sudoers.d/{SERVICE_NAME}"

# Legacy location — migrated to WG_DIR on first install after this change
_LEGACY_CONF  = "/etc/wireguard/wg0.conf"


def _get_service_user() -> str:
    try:
        return pwd.getpwuid(os.getuid()).pw_name
    except Exception:
        return "root"


def _get_outbound_iface() -> str:
    r = subprocess.run(["ip", "route", "show", "default"], capture_output=True, text=True)
    parts = r.stdout.split()
    try:
        return parts[parts.index("dev") + 1]
    except (ValueError, IndexError):
        return "eth0"


def _enable_ip_forward():
    subprocess.run(["sudo", "sysctl", "-w", "net.ipv4.ip_forward=1"], capture_output=True)
    subprocess.run(
        ["sudo", "tee", "/etc/sysctl.d/99-wireguard.conf"],
        input="net.ipv4.ip_forward=1\n", text=True, capture_output=True,
    )


def _conf_exists() -> bool:
    """Check whether wg0.conf is accessible via sudo (file is root-owned 600)."""
    r = subprocess.run(["sudo", "cat", WG_CONF], capture_output=True)
    return r.returncode == 0


def _install_sudoers():
    user = _get_service_user()
    rules = [
        f"# HostPanel WireGuard plugin — auto-generated by on_install",
        f"{user} ALL=(root) NOPASSWD: {WG_BIN} *",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/cat {WG_CONF}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/tee {WG_CONF}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/chmod 600 {WG_CONF}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/mkdir -p {PEERS_DIR}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/chmod 700 {PEERS_DIR}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/cat {PEERS_DIR}/*",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/tee {PEERS_DIR}/*",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/chmod 600 {PEERS_DIR}/*",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/rm -f {PEERS_DIR}/*",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/mv {PEERS_DIR}/* {PEERS_DIR}/*",
        f"{user} ALL=(root) NOPASSWD: /usr/sbin/sysctl -w net.ipv4.ip_forward=1",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/tee /etc/sysctl.d/99-wireguard.conf",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/systemctl daemon-reload",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/systemctl enable {SERVICE_NAME}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/systemctl start {SERVICE_NAME}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/systemctl stop {SERVICE_NAME}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/systemctl disable {SERVICE_NAME}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/systemctl restart {SERVICE_NAME}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/systemctl is-active {SERVICE_NAME}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/tee {SERVICE_DST}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/chmod 644 {SERVICE_DST}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/rm -f {SERVICE_DST}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/tee /tmp/hp-wg-sudoers",
        f"{user} ALL=(root) NOPASSWD: /usr/sbin/visudo -c -f /tmp/hp-wg-sudoers",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/tee {SUDOERS_DST}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/chmod 440 {SUDOERS_DST}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/rm -f {SUDOERS_DST}",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/cat /etc/wireguard/wg0.conf",
        f"{user} ALL=(root) NOPASSWD: /usr/bin/rm -rf {WG_DIR}",
    ]
    content = "\n".join(rules) + "\n"
    tmp = "/tmp/hp-wg-sudoers"
    subprocess.run(["sudo", "tee", tmp], input=content, text=True, capture_output=True)
    v = subprocess.run(["sudo", "visudo", "-c", "-f", tmp], capture_output=True)
    if v.returncode == 0:
        subprocess.run(["sudo", "tee", SUDOERS_DST], input=content, text=True, capture_output=True)
        subprocess.run(["sudo", "chmod", "440", SUDOERS_DST], capture_output=True)
        logger.info(f"WireGuard on_install: installed sudoers for user={user}")
    else:
        logger.warning(f"WireGuard on_install: sudoers validation failed: {v.stderr.decode()}")


def on_install():
    logger.info("WireGuard on_install: initialising")

    os.makedirs(WG_DIR, exist_ok=True)
    os.makedirs(PEERS_DIR, exist_ok=True)

    _enable_ip_forward()
    _install_sudoers()

    # Migrate conf from legacy /etc/wireguard location if present
    if not _conf_exists():
        legacy = subprocess.run(["sudo", "cat", _LEGACY_CONF], capture_output=True, text=True)
        if legacy.returncode == 0 and legacy.stdout.strip():
            if "10.8.0." not in legacy.stdout:
                subprocess.run(["sudo", "tee", WG_CONF], input=legacy.stdout, text=True, capture_output=True)
                subprocess.run(["sudo", "chmod", "600", WG_CONF], capture_output=True)
                logger.info("WireGuard on_install: migrated wg0.conf from /etc/wireguard → /opt/hostpanel/plugins/wireguard")
            else:
                logger.info("WireGuard on_install: legacy 10.8.0.x conf found, will regenerate")

    # Generate initial conf only on first install
    if not _conf_exists():
        iface = _get_outbound_iface()
        priv = subprocess.run([WG_BIN, "genkey"], capture_output=True, text=True)
        privkey = priv.stdout.strip()
        conf = (
            "[Interface]\n"
            "Address = 10.66.66.1/24\n"
            "ListenPort = 51820\n"
            f"PrivateKey = {privkey}\n"
            f"PostUp = sysctl -w net.ipv4.ip_forward=1; "
            f"iptables -A FORWARD -i wg0 -j ACCEPT; "
            f"iptables -t nat -A POSTROUTING -o {iface} -j MASQUERADE\n"
            f"PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; "
            f"iptables -t nat -D POSTROUTING -o {iface} -j MASQUERADE\n"
        )
        subprocess.run(["sudo", "tee", WG_CONF], input=conf, text=True, capture_output=True)
        subprocess.run(["sudo", "chmod", "600", WG_CONF], capture_output=True)
        logger.info(f"WireGuard on_install: generated wg0.conf (iface={iface})")

    if not os.path.exists(SERVICE_DST):
        svc_src = os.path.join(WG_DIR, "service", f"{SERVICE_NAME}.service")
        if os.path.exists(svc_src):
            try:
                with open(svc_src) as f:
                    content = f.read()
                subprocess.run(["sudo", "tee", SERVICE_DST], input=content, text=True, capture_output=True)
                subprocess.run(["sudo", "chmod", "644", SERVICE_DST], capture_output=True)
                logger.info(f"WireGuard on_install: installed service → {SERVICE_DST}")
            except Exception as e:
                logger.warning(f"WireGuard on_install: could not install service file: {e}")

    subprocess.run(["sudo", "systemctl", "daemon-reload"], capture_output=True)
    subprocess.run(["sudo", "systemctl", "enable", SERVICE_NAME], capture_output=True)
    subprocess.run(["sudo", "systemctl", "start", SERVICE_NAME], capture_output=True)
    logger.info("WireGuard on_install: complete")

    _sync_peers_to_conf()


def pre_uninstall(force: bool = False):
    logger.info(f"WireGuard pre_uninstall: force={force}")
    subprocess.run(["sudo", "systemctl", "stop", SERVICE_NAME], capture_output=True)
    subprocess.run(["sudo", "systemctl", "disable", SERVICE_NAME], capture_output=True)
    subprocess.run(["sudo", "rm", "-f", SERVICE_DST], capture_output=True)
    subprocess.run(["sudo", "systemctl", "daemon-reload"], capture_output=True)
    if os.path.isdir(WG_DIR):
        subprocess.run(["sudo", "rm", "-rf", WG_DIR], capture_output=True)
    subprocess.run(["sudo", "rm", "-f", SUDOERS_DST], capture_output=True)
    logger.info("WireGuard pre_uninstall: complete")


def _sync_peers_to_conf():
    try:
        from hostpanel_wireguard.plugin import _sync_conf_from_db
        added = _sync_conf_from_db()
        if added:
            logger.info(f"WireGuard lifecycle: re-added {added} peer(s) from DB to conf")
    except Exception as e:
        logger.warning(f"WireGuard lifecycle: peer sync failed: {e}")


def on_startup():
    _enable_ip_forward()
    result = subprocess.run(
        ["sudo", "systemctl", "is-active", SERVICE_NAME],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        logger.info("WireGuard on_startup: service not active, starting")
        subprocess.run(["sudo", "systemctl", "start", SERVICE_NAME], capture_output=True)
    else:
        logger.info("WireGuard on_startup: service is active")
    _sync_peers_to_conf()
